### PR TITLE
Resolves #48 Ensure only one PolicyConfigurationFactory will be instantiated.

### LINKED ISSUE #48: PolicyConfigurationFactory.getPolicyConfigurationFactory() is not thread safe.
As this method is responsible for creating the singleton PolicyConfigurationFactory if it is called more than once concurrently multiple instances can be created.

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by arjantijms** [comment]
@darranl I see that we still haven't merged this one in, but the ECA check is failing. Can you take a look?

**Comment by keilw** [comment]
Is this still relevant or can we close it, because it created a merge conflict, and there should be a code-complete state for Jakarta EE 9 soon?

**Comment by darranl** [comment]
@keilw yes this is still relevant as I don't believe a fix has been applied - I don't know if that ECA check updates I did go through the process a couple of times, I think I had to update my GitHub e-mail address to get it to match,

**Comment by keilw** [comment]
@darranl You may have to do it again unless @arjantijms is happy to resolve the merge conflicts manually, they usually can't be done on Github any more automatically. Also at some point the JEE9 milestone could mean it has to wait till a later version if it takes too long.

**Comment by arjantijms** [comment]
Unless someone else jumps in, I'll put this on my list to do soon.

There was a big discussion about this, and I do personally still think the handler itself should be stateless (and should be using the Subject if there's any state to keep track of), but I also understand we're not living in a perfect world so it would be good to accommodate JBoss/WildFly and potentially other users here.

**Comment by jeanouii** [comment]
Aside that I'm not a big fan of this big synchronized block with classloading work, I'll second you Arjan.
I'm not convinced it's a good change to apply.

**Comment by darranl** [comment]
The only time the synchonized block is actually hit is if the PolicyConfigurationFactory has not already been initialised so would either be hit just once or if it is hit by parallel threads it is doing it's job and those other threads have now avoided their own redundant class loading and instantiation most of which would be discarded.

**Comment by arjantijms** [comment]
@darranl the biggest problem is still:

"Darran Lofthouse (darran.lofthouse@****.com) is not covered by the necessary legal agreements in order to proceed."

I'll close this PR then. If you want, can you try to do a new PR? That should hopefully get rid of both the ECA issue and conflict.

**Pull request closed without merging**
